version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - Harpia

jobs:
  build:
    docker:
      - image: circleci/python:3.9.2
    working_directory: ~/workspace
    environment:
      SERVICE_NAME: influx_file_uploader
      SERVICE_VERSION: v1.0.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check variable
          command: echo ${PROJECT_ID}
      - run:
          name: Build docker image
          command: docker build -t ${SERVICE_NAME}:latest .
      - run:
          name: Set the tag for the image
          command: docker tag ${SERVICE_NAME} theharpia/${SERVICE_NAME}:${SERVICE_VERSION}
      - run:
          name: Login to dockerhub
          command: docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASS}
      - run:
          name: Push image to DockerHub
          command: docker push theharpia/${SERVICE_NAME}